#!/opt/pwn.college/bash

set -e

git config --global --add safe.directory /tmp/repo

# Check if /tmp/repo exists and is a directory
if [ ! -d /tmp/repo ]; then
    echo "[-] Do not delete the /tmp/repo directory!"
    exit 1
fi

commit_count=$(git rev-list --count HEAD)

if [ "$commit_count" -eq 2 ]; then
    last_commit_files=$(git show --pretty="" --name-only HEAD)
    if echo "$last_commit_files" | grep -q "part1.txt" \
       && echo "$last_commit_files" | grep -q "part2.txt" \
       && echo "$last_commit_files" | grep -q "part3.txt"; then
        echo "[+] Congratulations! The commit history has been successfully cleaned up! Here is your flag:"
        cat /flag
        exit 0
    else
        echo "[-] The last commit is missing required files!"
        exit 1
    fi
else
    echo "[-] The total number of commits is not 2 (must be initial commit + merge commit)!"
    exit 1
fi
