#!/opt/pwn.college/bash

if [ -f /tmp/answer ]; then
    if diff /tmp/answer /expected_answer >/dev/null; then
        echo "[+] Correct! Here is your flag:"
        cat /flag
    else
        echo "[-] The submitted git log is incorrect. Please try again!"
        exit 1
    fi
else
    echo "[-] /tmp/answer file not found!"
    exit 1
fi
