#!/opt/pwn.college/bash
set -e

found=$(git rev-parse HEAD)
expected=$(cat /challenge/bug_commit)

if [[ "$found" == "$expected" ]]; then
  echo "[+] Success! You found the commit that introduced the bug."
  echo -n "Your flag is: "
  cat /flag
else
  echo "[-] The current commit is not where the bug was first introduced."
  echo "Hint: Use git bisect + a script to locate it."
  exit 1
fi
